### ISSUE TITLE
Re-use nidmresults module?

### ISSUE THREAD

**Issue by cmaumet** [incf-nidash/nidm-api#12]
Could the [`nidmresults` module](https://github.com/incf-nidash/nidmresults) be re-used as part of the [nidm-api/results.py](https://github.com/incf-nidash/nidm-api/blob/master/nidm/results.py)?

**Comment by vsoch** [comment]
How about instead of having dependency hell, I migrate the nimresults module into the api "results.py"?

**Comment by cmaumet** [comment]
The thing is the [NIDM-Results exporter for FSL](https://github.com/incf-nidash/nidm-results_fsl/) (and [ AFNI](https://github.com/incf-nidash/nidm-results_afni/)) also depend on [`nidmresults`](https://github.com/incf-nidash/nidmresults). So if we move `nidmresults` here then we would have to import the whole `nidm-api` in `nidm-results_fsl` and `nidm-results_afni`... 

Unless you can see an easier solution around it?

**Comment by vsoch** [comment]
I think it's a necessary move if we are to have a single, reliable source for these functions, which is essential for the user. It's just changing a few lines in the setup and imports, I'm happy to do this as well if you point me to where it is used.

**Comment by vsoch** [comment]
If a developer wants to use nidm results, he/she shouldn't have to look through all these packages in our repo. It should be a simple:

```
  from nidm.results import *
```

We should keep things as is and I can start doing migrations, and when we are happy with the nidm api we can do final switches. What do you think?

**Comment by cmaumet** [comment]
I do understand the vision, I am just wondering if now is the right time to have those consolidated in a single repository. Our NIDM components (expe, workflow, results) are at different level of maturity and I can also see the benefit of keeping a separate repository for each component while we are still developing them. Another related issue being to keep the number of dependencies at a minimum (e.g. if `nidm-results_fsl` is included in FSL, do we really need to have a dependency on `flask`?)...

That's why I was thinking about imports rather than copying the code over here... But I am open for discussion and would be happy to hear what others think?

**Comment by nicholsn** [comment]
@cmaumet raises a good point. I just wen't through and installed the dependencies for nidm-api and there is quite a bit that goes into it. The original design of the nidm api was just that, a RESTful API for providing views of NIDM object models. 

This seems to be evolving into a full blown query application and not just a programming interface, no?  I'm all for seeing where this goes, but think it is important to realize that we should likely modularize at some point. 

Part of that may be to import nidmresults for the time being or just let it exist on its own as a specific tool, but I think we'll want a consistent api for the nidm library and I'm not sure the current design of nidmresults is scalable. For example, nidmresults explicitly models nidm objects and attributes, which may not be possible in nidm-experiment as there could be 10s of thousands of terms if we include DICOM and cognitive assessments. 

Another idea would be to potentially generate clients from OWL files in a similar way that [NIX](https://github.com/G-Node/nixpy) or the other tools we heard about at the task force meeting...

**Comment by vsoch** [comment]
@nicholsn - I had added the results.py, workflow.py, etc, at your suggestion, and looking at the different levels of maturity for the different applications, I now think it's a better idea to (at least for now) leave them separate. I would like to propose to remove these functions from the current nidm-API. Sound good?

**Comment by nicholsn** [comment]
remove them if you like or leave them as placeholders, we probably need to have a discussion about the api design on a call. The motivation for each of these modules would be to provide an object that has access to the respective queries for a nidm component. With that in mind, it may make sense to just have a query module with just classes for each component. not sure exactly, but something like this

```
from nidm.query import ExperimentQueries
exp = ExperimentQueries()
exp.list_queries()
query = exp.get_query('query_id')
result = query('input_graph")
```

**Comment by vsoch** [comment]
I see what you are thinking - so the basic modules would basically just be wrappers for selecting a particular subject of queries, which is just anything in the nidm-query/experiment folder. The modules would basically give more "human interpretable" function imports. I don't see why the line:

```
    query = exp.get_query('query_id')
```

would need to be within each of experiment, workflow, and results. It would be just within the query.py. But within experiment, for example, we might want to have functions to give nice names to specific queries, for example:

```
  from nidm.experiment import ExperimentQueries
  from nidm.query import do_query

  exp = ExperimentQueries()
  exp.list_queries()
  do_query("XXX")
```

Something like that?

**Comment by nicholsn** [comment]
yes, but thinking about it more, maybe a full module per nidm component is overboard? Could probably just have query objects in the query module.  I suppose you don't need a separate Experiment/Workflow/Results object really, rather filter based on the component/model indicated in the query json. So, just playing around with ideas here:

```
from nidm.query import Queries

experiment_queries = Queries(component='experiment')
[<query_obj>, <query_obj> <query_obj>]
select_queries = Queries(type='select')
query_object = experiment_queries[0]
query_object.iri
"http://.....3e425tqt.json"
query_object.title
"query title"
query_object.type
"construct"
query_object.component
'nidm experiment'
query_object.do_query('turtle.ttl')
```

**Comment by vsoch** [comment]
Haha nolan, the separate results.py etc was your idea, I'm on board with drop-kicking / exploding / launching them out into outer-space (aka, removing them) :)

I love the example you just gave - that looks a little bit like Django queries, so people would be comfortable with it. For the first round, I will implement something like this.

**Comment by nicholsn** [comment]
and maybe they'll come back when needed - being able to change ones mind is
a beautiful thing =)

**Comment by vsoch** [comment]
making a query class is not something I like the idea of, because it means we need to hard code the things we think are important as variables in the API. A better idea is to return a json data structure with the queries that can be queried almost equivalently, but without the objects with hard coding.

**Comment by vsoch** [comment]
ok take a look here:

https://github.com/incf-nidash/nidm-api/blob/master/nidm/query.py#L28

I made a Queries object that can be easily used to work with a subset of queries. I don't really want to work on this this weekend, but feel free to start developing it!

**Comment by nicholsn** [comment]
sounds like a plan, keep it simple

**Comment by cmaumet** [comment]
So we are on the same page regarding the different nidm components. Great! Coming back to `nidmresults`, if you can think of developments that could make your life easier on this side. Please let me know!

**Comment by vsoch** [comment]
yes! I removed the extraneous scripts. I'm going to close this issue.
