### ISSUE TITLE
Include json-ld support

### ISSUE THREAD

**Issue by nicholsn** [incf-nidash/nidm-api#17]
https://github.com/RDFLib/rdflib-jsonld

**Comment by vsoch** [comment]
The files are jsonld, I just used a different extension because nobody sees those in the wild.

**Comment by nicholsn** [comment]
right but for serializing/parsing you'll want to include the library as a dependency. For example, with content negotiation you'll need this for API responses

**Comment by vsoch** [comment]
oh yes, I see. Let me see if adding it breaks readthedocs again :O)

**Comment by vsoch** [comment]
It breaks it, but I can add it as a pip command post install, see [here](https://github.com/vsoch/nidm-api/blob/master/nidm/script/post_install.py). Can you think of a better way to do this?

Here is an example of a successful build:
https://readthedocs.org/projects/nidm/builds/3444416/
(look under the setup.py to see that not having the curl installed doesn't stop the build), but on a user machine this would work fine.

and an unsuccessful build:
https://readthedocs.org/projects/nidm/builds/3444406/

**Comment by nicholsn** [comment]
I think solution is fine, don't understand why tho. Does rtd not have curl
available?

**Comment by vsoch** [comment]
Nope, it appears not.

**Comment by vsoch** [comment]
Let me try running it outside of a venv, that might do the trick.

**Comment by nicholsn** [comment]
is wget available? you could do something with miniconda like:
https://github.com/nipy/nipype/blob/master/.travis.yml#L11

**Comment by vsoch** [comment]
I think the solution is fine for now, it's not worth it (at least now) to try and come up with a second solution to do the same thing. I'm going to close this for now!
